version: '3'

services:

  # db:
  #   image: mysql:5.7
  #   container_name: php_db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - "3306:3306"
  
  # PHP Apache Service
  phpapp:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/