version: '3'

services:

  # MySQL Database Service
  db:
    build:
      context: .
      dockerfile: Dockerfile.sql
    # image: mysql:5.7
    container_name: php_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'users_database' # Create this database on startup
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      # MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
  
  # PHP Apache Service
  phpapp:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/

  # PHP MyAdmin Service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password       